### ISSUE TITLE
Error when i try to load gamecommand on streamlabs

### ISSUE THREAD

**Issue by ther3y3s** [PoodleSlayer/StreamLabsScripts#1]
Hi, i tried to load this script on chatbot but doesn't work. I get this error: "reference to an object not set on an object instance" (i use google to translate this error, i hope you can understand)

**Comment by PoodleSlayer** [comment]
Sorry about that! This script isn't actually finished yet, I was just updating the repo so someone else could take a look. I should have it finished in the next few days though, and I'll mark this as closed when I get a chance to test it and make sure this is fixed.

Thanks for the issue though, and I'm glad you're interested in the project!

**Comment by PoodleSlayer** [comment]
Alright this should be fixed now! I also included a README for this script since it can be a little complicated to understand. This is still a work-in-progress so I will be making changes to it based on feedback from people so feel free to let me know any ideas you might have for it.
